### ISSUE TITLE
Find a better way to remove the column in down.sh

### ISSUE THREAD

**Issue by TheDoctorsLife** [mgattozzi/alchemist#56]
After adding Debian I realized the current way won't work, lets say I remove the void migration, well now Debian also had its migration removed.

**Comment by mgattozzi** [comment]
I think this might be because you forgot to add the void column to the table when you dropped it. I commented on the PR regarding your drop statement. Add in the void column to the table when it gets dropped in the sql migration. Make sure void is a selected column for the insert to the new table as well before the rename.

The docs are a good example. Verbatim following of them though might lead to things like this. Let me know if my suggestion makes sense and helps solve the problem. If it does close out the issue. You could do a separate pr for the docs about this issue so that future maintainers can understand when adding a new distro what to do.

**Comment by TheDoctorsLife** [comment]
My issue really falls that for every new distro, every migration down.sh needs to be changed to add it. I would like to see another way of handling it.

**Comment by mgattozzi** [comment]
No it shouldn't need to change at all. Each migration is it's own snapshot of the db. Each one is applied in order. The down.sql is to revert the current migration not all migrations.

**Comment by TheDoctorsLife** [comment]
So if I were to have diesel run the down for void, it wouldn't delete say debian because it dropped the table?

**Comment by mgattozzi** [comment]
Running diesel migration revert drops the most recent migration. If you set
the down.sql file right out will only drop defiant which is the newest
addition. Doing revert again would drop void since that's our next most
recent migration. That number on creating a new migration is a time stamp
telling diesel the order to apply or revert changes in. You wouldn't be
able to drop void without dropping debian first

**Comment by TheDoctorsLife** [comment]
Closing due to #73
